### ISSUE TITLE
Certificate chains

### ISSUE THREAD

**Issue by bmomjian** [thusoy/postgres-mitm#2]
Can you improve this script to output the entire server certificate chain, and not just the server certificate?  I think Python's get_ca_certs() might allow this.  However, this seems to say it is not possible:

   http://stackoverflow.com/questions/19145097/getting-certificate-chain-with-python-3-3-ssl-module

**Comment by thusoy** [comment]
I did some testing, and you're right, this is not exposed through the python ssl module. I'm not working actively on this, but if you do get something working (maybe by using the cryptography library), I'd take a PR.

**Comment by bmomjian** [comment]
On Fri, May  5, 2017 at 07:29:23AM -0700, Tarjei Husøy wrote:
> I did some testing, and you're right, this is not exposed through the python
> ssl module. I'm not working actively on this, but if you do get something
> working (maybe by using the cryptography library), I'd take a PR.

I mentioned your tool in my TLS talk, slide 75:

	https://momjian.us/main/writings/pgsql/tls.pdf

I found a way to show multiple certificates in a single file a different
way.

-- 
  Bruce Momjian  <bruce@momjian.us>        http://momjian.us
  EnterpriseDB                             http://enterprisedb.com

+ As you are, so once was I.  As I am, so you will be. +
+                      Ancient Roman grave inscription +

**Comment by thusoy** [comment]
Thanks for the shoutout, I'm glad it was useful and that you figured out a solution!
