### ISSUE TITLE
Relicense to Hippocratic License

### ISSUE THREAD

**Issue by thusoy** [thusoy/postgres-mitm#8]
Having a license that restricts usage by parties infringing upon the UN's declaration of human rights is more important for a project like this than most, given how easily it can be used for abuse.

Since existing code is under MIT and the Hippocratic License is basically MIT with an extra clause, the practical effect from this change is (hopefully) minimal. I still need approval from existing contributors to relicense though, so @ankane and @xbglowx, are you okay with relicensing your contributions?

**Comment by xbglowx** [comment]
SGTM

**Comment by ankane** [comment]
👍

**Comment by thusoy** [comment]
Great, thanks!
